# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2dd4a4664154593c7ee00c23bbb396b5d455fb0bd538cb94561cabbed3587543175db616794bb5c0f3bae3f7a7e9adc4fda1f7bd48646fc9f154d69ec4df103

test:
  secret_key_base: b08517662fd88fbb1732d2e5151cc806022c128828157e5345f4690b0034ec962d29ab0fc08fc9becc5ca06bc9cfc712dee9ae5e39c2e5366b4796fc292c6102

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
